### ISSUE TITLE
Headless is annoying

### ISSUE THREAD

**Issue by suiramdev** [ibadus/42-check-in#3]
Hey, thanks for this script, we had the same idea.
I started it and saw that puppeteer is opening the web page visually too. This could be quite annoying for someone who wants to run it on his computer while working.

Can't we just set the `headless` to `true`? It would work the same way:
```js
let browser = await puppeteer.launch({
   headless: true, // to true instead of false
```

**Comment by suiramdev** [comment]
It's not much, anyone could set it himself, but that would help the noncoders.

**Comment by suiramdev** [comment]
It only opens it only for the log-in, I didn't know that.

**Comment by ibadus** [comment]
Hey, yeah it only opens on login then the window close it self. The reason i did that i to allow non coders to see what's happening with their credentials. And help them debug things if something goes wrong on login (i.e. wrong password). Then it also open a non headless browser on a new checkin detection and will try to login and subscribe to the available checkin, i made it also not headless to allow the user to take control of the browser trying to automate the subscription.
But if you want you could PR to switch the login to a full request method to gain speed / improve the bot.
