### ISSUE TITLE
Pass Captcha ?

### ISSUE THREAD

**Issue by MathieuSoysal** [ibadus/42-check-in#5]
Hello,

I wanted to know if this script pass the captcha test when we want to subscribe for the check-in ?

**Comment by ibadus** [comment]
Hello,

The current code doesn't support solving any captchas, but feel free to open a PR to add this feature

**Comment by MathieuSoysal** [comment]
So it doesn't work with the current version of the Check-in website?

Because we need to pass a captcha to sign into a Check-in.

Or does this project use a solution to not do the captcha and sign to Check-in without it?
